name: Clonar Proyecto

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de tu repo
        uses: actions/checkout@v4

      - name: Clonar repo original
        run: |
          git clone https://github.com/maxifuentes2/presentacionFinal.git temp_repo

      - name: Copiar archivos y pushear
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Copiar todo menos la carpeta .git del repo original
          cp -r temp_repo/* .
          rm -rf temp_repo
          
          # Subir los cambios a tu repo
          git add .
          git commit -m "Copia completa de archivos" || echo "Sin cambios"
          git push origin main
